### PR TITLE
1199282 - ms.topic update

### PR DESCRIPTION
**Pull request by cmcclister**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@cmcclister : Thanks for your contribution to the Azure documentation! The author, @, has been notified to review your proposed change.

**Comment by cmcclister** [comment]
#sign-off Production 1199282

**Comment by PRMerger13** [comment]
@cmcclister: I'm sorry - only the author of this article, @mbaldwin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by cmcclister** [comment]
Thank you for clarifying. This isn't urgent.

**Pull request merged**
