### PR TITLE
Update whats-new.md

### PR DESCRIPTION
**Pull request by morRubin**
adding new MDI detections published in July

### CODE REVIEW

**Comment by andremieth** [comment]
I count 6 new detections, not 7, did i missed one?

**Comment by morRubin** [comment]
My bad. changed to 6

**Comment by Court72** [comment]
@batamig

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by batamig** [comment]
Hi @morRubin, we prefer our internal contributors to make updates via the private repo only. Please ping me on Teams if you need details about how to recreate this there. Thanks!

**Comment by batamig** [comment]
closing as duplicated from private repo

**Pull request closed without merging**
