### PR TITLE
Update install-sensor.md

### PR DESCRIPTION
**Pull request by hpanao**
in line 98 the path is logs path is not correct.

%appdata% points to C:\Users\USERNAME\AppData\Roaming

%localappdata% points to C:\Users\USERNAME\AppData\Local\

for that reason the doc should refer the customers to %localappdata%\Temp where the logs actually reside, rather than %AppData%\Local\Temp that is a non-existing path/folder.

### CODE REVIEW

**Comment by Court72** [comment]
@batamig

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by batamig** [comment]
@martin77s can you please verify this fix? Thanks!

**Comment by martin77s** [comment]
#sign-off

**Comment by batamig** [comment]
#sign-off

**Pull request merged**
