### PR TITLE
replace Prremier with Unified

### PR DESCRIPTION
**Pull request by rstamp**
let's see if that works, first time github user, sorry :-)

### CODE REVIEW

**Comment by Jak-MS** [comment]
@batamig 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.

@rstamp - to fix the link issue reported by validation, just remove the "https://learn.microsoft.com" from the link. Start it with "/services-hub" 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by rstamp** [comment]
[heart]         Robert Stampfer reacted to your message:
________________________________

**Comment by rstamp** [comment]
great to see we're making progress, thanks!
one related question: can we get the legacy thumbs up feedback icon removed on all pages?
I tried to use it first to submit a change request for the page, but it's not the same as github.
mdi-feedback

**Comment by rstamp** [comment]
@batamig any update on this please?

**Comment by batamig** [comment]
Thanks for your contribution @rstamp! And welcome to the world of GitHub pull requests and open source docs :)
I'm approving the PR and signing off, so it'll get merged in a coming publish.

Re your question about the feedback button, these sorts of elements are global and are rolling out across Microsoft docs. If you have feedback about them, please do send that feedback in so that it gets to the right place.

#sign-off

**Comment by ShannonLeavitt** [comment]
Thank you, @rstamp

**Pull request merged**
