### PR TITLE
Update configure-windows-event-collection.md

### PR DESCRIPTION
**Pull request by fngrhth**
Submitted via Learn Editor.

### CODE REVIEW

**Comment by fngrhth** [comment]
Changing heading size since otherwise it looks like this section belongs to AD CS server

**Comment by Jak-MS** [comment]
@fngrhth - can you mark this "Ready for review" and take it out of draft mode, when you're ready. I also recommend tagging @batamig when it's out of draft mode.

@batamig 
- Can you review this PR? (when it's ready)
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by fngrhth** [comment]
@batamig

**Comment by batamig** [comment]
#sign-off

**Pull request merged**
