### PR TITLE
Add problem after change ATA Certificate

### PR DESCRIPTION
**Pull request by dostshell**
If you want, edit the redaction, this it's the idea. Thanks for the help!

### CODE REVIEW

**Comment by PRMerger20** [comment]
@dostshell : Thanks for your contribution to the Azure documentation! The author, @rkarlin, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@dostshell : Thanks for your contribution to the Azure documentation! The author, @rkarlin, has been notified to review your proposed change.

**Comment by rkarlin** [comment]
Thanks. I checked with the product team and they will propose a solution to this error. Thanks.

**Comment by ktoliver** [comment]
@rkarlin - Can this PR be closed? Thanks.

**Comment by rkarlin** [comment]
yes, thanks

**Pull request closed without merging**
