### PR TITLE
Adding 'Data exfiltration over SMB' Detection

### PR DESCRIPTION
**Pull request by husamhilal**
Adding instructions to simulate stealing NTDS.dit and how AATP detects that.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@husamhilal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@husamhilal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@husamhilal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@husamhilal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@husamhilal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@husamhilal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@husamhilal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by husamhilal** [comment]
Hello @shsagir, 
Can we push this commit to live, please?
Please let me know if there is anything missing. Thanks a lot!

**Comment by shsagir** [comment]
@husamhilal Thanks for your feedback. After investigating, we've discovered the proposed changes are part of the [exfiltration detections](https://docs.microsoft.com/azure-advanced-threat-protection/atp-exfiltration-alerts#data-exfiltration-over-smb-external-id-2030) and not part of the LMP detections. Since this tutorial is about LMP, we respectfully decline to update this topic. But, thanks again; we always appreciate feedback on our documentation.
Because we cannot change the referenced page to include the information and functionality that you're asking for, we are closing this issue. We do thank you for your input, however; we always appreciate feedback on our documentation.

**Pull request closed without merging**
